Repository MarkBind/markbind, pull requests merged in 2020-03, with the labels that each got.

#1051 Render plugins on dynamic resources
  src/Page.js
  test/functional/test_site/expected/needsrenderedplugin._include_.html
  test/functional/test_site/expected/requirements/SpecifyingRequirements._include_.html
  test/functional/test_site/expected/requirements/notInside._include_.html
  test/functional/test_site/expected/siteData.json
  test/functional/test_site/expected/sub_site/index._include_.html
  test/functional/test_site/expected/testImportVariables._include_.html
  test/functional/test_site/expected/testIncludePluginsRendered.html
  test/functional/test_site/expected/testPanels/NestedPanel._include_.html
  test/functional/test_site/expected/testPanels/NormalPanelContent._include_.html
  test/functional/test_site/expected/testPanels/PanelNormalSource._include_.html
  test/functional/test_site/expected/testPanels/PanelSourceContainsSegment._include_.html
  test/functional/test_site/expected/testPanels/boilerTestPanel._include_.html
  test/functional/test_site/expected/testPanels/notInside._include_.html
  test/functional/test_site/needsrenderedplugin.md
  test/functional/test_site/site.json
  test/functional/test_site/testIncludePluginsRendered.md
Labels: pr.BugFix 🐛

#1034 Add heading and line highlighting to code blocks
  asset/css/markbind.css
  docs/userGuide/syntax/code.mbdf
  src/lib/markbind/src/lib/markdown-it/index.js
  test/functional/test_site/expected/markbind/css/markbind.css
  test/functional/test_site_algolia_plugin/expected/markbind/css/markbind.css
  test/functional/test_site_convert/expected/markbind/css/markbind.css
  test/functional/test_site_expressive_layout/expected/markbind/css/markbind.css
  test/functional/test_site_templates/test_default/expected/markbind/css/markbind.css
  test/functional/test_site_templates/test_minimal/expected/markbind/css/markbind.css
Labels: pr.Enhancement 📈

#1047 Implement an api to ignore text in certain tags
  docs/userGuide/usingPlugins.md
  src/Page.js
  src/Site.js
  src/lib/markbind/src/lib/markdown-it-shared/markdown-it-escape-special-tags.js
  src/lib/markbind/src/patches/htmlparser2.js
  test/functional/test_site_special_tags/_markbind/plugins/testSpecialTag.js
  test/functional/test_site_special_tags/expected/index.html
  test/functional/test_site_special_tags/expected/markbind/css/bootstrap-vue.min.css
  test/functional/test_site_special_tags/expected/markbind/css/bootstrap.min.css
  test/functional/test_site_special_tags/expected/markbind/css/bootstrap.min.css.map
  test/functional/test_site_special_tags/expected/markbind/css/github.min.css
  test/functional/test_site_special_tags/expected/markbind/css/markbind.css
  test/functional/test_site_special_tags/expected/markbind/css/octicons.css
  test/functional/test_site_special_tags/expected/markbind/css/page-nav.css
  test/functional/test_site_special_tags/expected/markbind/css/site-nav.css
  test/functional/test_site_special_tags/expected/markbind/fontawesome/css/all.min.css
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-brands-400.eot
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-brands-400.svg
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-brands-400.ttf
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-brands-400.woff
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-brands-400.woff2
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-regular-400.eot
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-regular-400.svg
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-regular-400.ttf
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-regular-400.woff
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-regular-400.woff2
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-solid-900.eot
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-solid-900.svg
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-solid-900.ttf
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-solid-900.woff
  test/functional/test_site_special_tags/expected/markbind/fontawesome/webfonts/fa-solid-900.woff2
  test/functional/test_site_special_tags/expected/markbind/glyphicons/css/bootstrap-glyphicons.min.css
  test/functional/test_site_special_tags/expected/markbind/glyphicons/fonts/glyphicons-halflings-regular.eot
  test/functional/test_site_special_tags/expected/markbind/glyphicons/fonts/glyphicons-halflings-regular.svg
  test/functional/test_site_special_tags/expected/markbind/glyphicons/fonts/glyphicons-halflings-regular.ttf
  test/functional/test_site_special_tags/expected/markbind/glyphicons/fonts/glyphicons-halflings-regular.woff
  test/functional/test_site_special_tags/expected/markbind/glyphicons/fonts/glyphicons-halflings-regular.woff2
  test/functional/test_site_special_tags/expected/markbind/js/bootstrap-utility.min.js
  test/functional/test_site_special_tags/expected/markbind/js/bootstrap-vue.min.js
  test/functional/test_site_special_tags/expected/markbind/js/polyfill.min.js
  test/functional/test_site_special_tags/expected/markbind/js/setup.js
  test/functional/test_site_special_tags/expected/markbind/js/vue-strap.min.js
  test/functional/test_site_special_tags/expected/markbind/js/vue.min.js
  test/functional/test_site_special_tags/expected/siteData.json
  test/functional/test_site_special_tags/index.md
  test/functional/test_site_special_tags/site.json
  test/functional/test_sites
Labels: pr.NewFeature 🆕

#1092 Fix refactor to processDynamicResources
  src/lib/markbind/src/parser.js
Labels: p.Urgent
