Repository MarkBind/markbind, pull requests merged in 2020-04, with the labels that each got.

#1169 Update tests for v2.13.1
  test/functional/test_site/expected/markbind/css/markbind.css
  test/functional/test_site_algolia_plugin/expected/markbind/css/markbind.css
  test/functional/test_site_convert/expected/markbind/css/markbind.css
  test/functional/test_site_expressive_layout/expected/markbind/css/markbind.css
  test/functional/test_site_special_tags/expected/markbind/css/markbind.css
  test/functional/test_site_templates/test_default/expected/markbind/css/markbind.css
  test/functional/test_site_templates/test_minimal/expected/markbind/css/markbind.css
Labels: pr.CodeMaintenance 🛠

#1089 bugfix: Fix hrefs for headings with angular brackets
  src/lib/markbind/src/parser.js
Labels: pr.BugFix 🐛

#1158 Update devGuide.md
  docs/devGuide/devGuide.md
Labels: pr.DocsUpdate 📃

#1100 Inline puml
  docs/userGuide/puml.md
  package-lock.json
  package.json
  src/plugins/default/markbind-plugin-plantuml.js
  src/util/pluginUtil.js
  test/functional/test_site/expected/9c9e77fc0a983cb6b592e65733787bec.png
  test/functional/test_site/expected/index.html
  test/functional/test_site/expected/inline-output.png
  test/functional/test_site/expected/testPlantUML.html
  test/functional/test_site/testPlantUML.md
Labels: pr.NewFeature 🆕

#1148 Remove fixed bugs from test\functional\test_site\bugs\index.md`
  test/functional/test_site/bugs/index.md
  test/functional/test_site/bugs/modal.md
  test/functional/test_site/expected/bugs/index.html
  test/functional/test_site/expected/siteData.json
  test/functional/test_site/expected/testIncludeMultipleModals.html
  test/functional/test_site/expected/testPopoverTrigger.html
  test/functional/test_site/requirements/testModal.md
  test/functional/test_site/site.json
  test/functional/test_site/testIncludeMultipleModals.md
  test/functional/test_site/testPopoverTrigger.md
Labels: pr.CodeMaintenance 🛠

#1116 Upgrade js-beautify and provide option to turn it off
  docs/userGuide/siteConfiguration.md
  package-lock.json
  package.json
  src/Page.js
  src/Site.js
  test/functional/test_site/expected/bugs/index.html
  test/functional/test_site/expected/index.html
  test/functional/test_site/expected/requirements/NonFunctionalRequirements._include_.html
  test/functional/test_site/expected/requirements/SpecifyingRequirements._include_.html
  test/functional/test_site/expected/requirements/UserStories._include_.html
  test/functional/test_site/expected/requirements/testBaseUrlInIncludeSrc._include_.html
  test/functional/test_site/expected/sub_site/index._include_.html
  test/functional/test_site/expected/sub_site/index.html
  test/functional/test_site/expected/sub_site/nested_sub_site/index.html
  test/functional/test_site/expected/sub_site/testReuse._include_.html
  test/functional/test_site/expected/testAfterSetup.html
  test/functional/test_site/expected/testAnchorGeneration.html
  test/functional/test_site/expected/testAntiFOUCStyles.html
  test/functional/test_site/expected/testCodeBlocks.html
  test/functional/test_site/expected/testEmptyFrontmatter.html
  test/functional/test_site/expected/testExternalScripts.html
  test/functional/test_site/expected/testImportVariables._include_.html
  test/functional/test_site/expected/testImportVariables.html
  test/functional/test_site/expected/testIncludeMultipleModals.html
  test/functional/test_site/expected/testIncludePluginsRendered.html
  test/functional/test_site/expected/testLayouts.html
  test/functional/test_site/expected/testLayoutsOverride.html
  test/functional/test_site/expected/testPanels/NestedPanel._include_.html
  test/functional/test_site/expected/testPanelsWithImportedVariables.html
  test/functional/test_site/expected/testPlantUML.html
  test/functional/test_site/expected/testPopoverTrigger.html
  test/functional/test_site/expected/testThumbnails.html
  test/functional/test_site/expected/testTooltipSpacing.html
  test/functional/test_site/expected/test_md_fragment.html
  test/functional/test_site_algolia_plugin/expected/index.html
  test/functional/test_site_convert/expected/Home.html
  test/functional/test_site_convert/expected/Page-1.html
  test/functional/test_site_convert/expected/_Footer.html
  test/functional/test_site_convert/expected/_Sidebar.html
  test/functional/test_site_convert/expected/about.html
  test/functional/test_site_convert/expected/contents/topic1.html
  test/functional/test_site_convert/expected/contents/topic2.html
  test/functional/test_site_convert/expected/contents/topic3a.html
  test/functional/test_site_convert/expected/contents/topic3b.html
  test/functional/test_site_convert/expected/index.html
  test/functional/test_site_expressive_layout/expected/index.html
  test/functional/test_site_special_tags/expected/index.html
  test/functional/test_site_templates/test_default/expected/contents/topic1.html
  test/functional/test_site_templates/test_default/expected/contents/topic2.html
  test/functional/test_site_templates/test_default/expected/contents/topic3a.html
  test/functional/test_site_templates/test_default/expected/contents/topic3b.html
  test/functional/test_site_templates/test_default/expected/index.html
  test/functional/test_site_templates/test_minimal/expected/index.html
Labels: pr.Enhancement 📈

#1156 Expand test extensions and fix whitespace checks
  package-lock.json
  package.json
  test/functional/testUtil/diffChars.js
  test/functional/testUtil/diffHtml.js
  test/functional/testUtil/diffPrinter.js
  test/functional/testUtil/test.js
Labels: pr.BugFix 🐛

#1170 Fix links in contributing.md and add code of conduct to siteNav
  docs/_markbind/layouts/devGuide/navigation.md
  docs/_markbind/navigation/devGuideSections.md
  docs/devGuide/contributing.md
  docs/dg-site.json
Labels: pr.DocsUpdate 📃

#1160 Move preprocessThumbnails to componentParser
  src/lib/markbind/src/parsers/componentParser.js
  src/lib/markbind/src/preprocessors/componentPreprocessor.js
  test/functional/test_site/expected/testThumbnails.html
Labels: pr.CodeMaintenance 🛠

#1215 Make highlighting effective for code-formatted text
  asset/css/markbind.css
  test/functional/test_site/expected/markbind/css/markbind.css
  test/functional/test_site_algolia_plugin/expected/markbind/css/markbind.css
  test/functional/test_site_convert/expected/markbind/css/markbind.css
  test/functional/test_site_expressive_layout/expected/markbind/css/markbind.css
  test/functional/test_site_special_tags/expected/markbind/css/markbind.css
  test/functional/test_site_templates/test_default/expected/markbind/css/markbind.css
  test/functional/test_site_templates/test_minimal/expected/markbind/css/markbind.css
Labels: pr.Enhancement 📈

#1204 Update the build steps in the maintainer guide
  docs/devGuide/maintainerGuide.md
Labels: pr.DocsUpdate 📃
